FROM balenalib/#{platform}-debian:stretch-build-20190215

RUN set -x \
	&& buildDeps=' \
		curl \
		gcc \
		libbz2-dev \
		libc6-dev \
		libncurses-dev \
		libreadline-dev \
		libsqlite3-dev \
		libssl-dev \
		liblzma-dev \
		libffi-dev \
		make \
		xz-utils \
		zlib1g-dev \
		python python-dev python-pip python-setuptools ca-certificates patch \
	' \
	&& install_packages -y $buildDeps

COPY build.sh /